### ISSUE TITLE
Add website translations

### ISSUE THREAD

**Issue by Chevyself** [ElMedievo/Website#5]
Let's make el medievo mr. worldwide

**Comment by BGMP** [comment]
# In progress over @ [Crowdin](https://crowdin.com/project/medievo) <img src="https://camo.githubusercontent.com/cc64afbc0654db91c3a5c955c1af5c77952c5237/68747470733a2f2f6261646765732e63726f7764696e2e6e65742f6d65646965766f2f6c6f63616c697a65642e737667">

**Comment by BGMP** [comment]
I have decided we will not require this, at least for now.
