### ISSUE TITLE
fix "la experiencia se jugable" -> "la experiencia sea* jugable"

### ISSUE THREAD

**Issue by BenjaFerrada** [ElMedievo/Website#6]
![fix](https://user-images.githubusercontent.com/43196058/61833415-3ca48400-ae42-11e9-9413-22bf7180dce5.PNG)

**Comment by BGMP** [comment]
Fixed. https://github.com/ElMedievo/Website/commit/2effcc98a3144606b04013326c0144ba0068ea9d
